book/book/urls.py
import imp
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import url
# from django.views.static import serve

from report.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('books/', books, name="books"),
    path('author/<str:id>', avtors, name="avtors"),
    path('authors/', authors, name="authors"),
    path('books_item/<int:id>/', item_books, name="item_books"),

    path('category/', category, name="category"),
    path('category/<int:id>/', fiter_book, name="fiter_book"),
    path('about-us/', aboute, name="aboute"),
    path('search/', search_books, name="search_books"),

    path('login/', login_profile, name='login'),
    path('logout/', logout_profile, name='logout'),

    path('my_books/', my_books, name='my_books'),
    path('my_books/create/', create_books, name='create_books'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

book/report/models.py
from django.db import models
from django.contrib.auth.models import User


class Categories(models.Model):

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    slug = models.SlugField(unique=True, verbose_name='slug название', null=True)
    title = models.CharField(max_length=100, verbose_name='название категотрии')

    def __str__(self):
        return f'{self.title}'

class Book(models.Model):
     
    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'

    title = models.CharField(max_length=300, verbose_name='заголовок')
    desc = models.TextField(verbose_name='описание')
    date = models.DateField(verbose_name='дата добавление', auto_now_add=True)
    file = models.FileField(verbose_name='файл', upload_to='file/', blank=True)
    image = models.ImageField(verbose_name='изображения', upload_to='image/', blank=True)
    author = models.ForeignKey('Avtor', on_delete=models.PROTECT, verbose_name='автор', null=True,)
    category = models.ForeignKey('Categories', on_delete=models.PROTECT, null=True, verbose_name='категория')
    author_site = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор', null=True)


    def __str__(self):
        return f'{self.title}'


class Works(models.Model):
    
    class Meta:
        verbose_name = 'автор-работа'
        verbose_name_plural = 'автор-работы'

    title = models.CharField(max_length=100, verbose_name='название книга')
    image = models.ImageField(verbose_name='изображения', upload_to='image/', blank=True)
    year = models.CharField(max_length=100, verbose_name='год издания')
    content =  models.TextField(verbose_name='контент')

    def __str__(self):
        return f'{self.title}'

class Avtor(models.Model):
    
    class Meta:
        verbose_name = 'автор'
        verbose_name_plural = 'авторы'
        
    title = models.CharField(max_length=100, verbose_name='имя автора')
    avtor = models.TextField(verbose_name='биография')
    img_Avtor = models.ImageField(verbose_name='изображения', upload_to='image/', blank=True)
    year_avtor = models.CharField(max_length=300, verbose_name='годы жизни', null=True)
    info = models.ManyToManyField('Works', verbose_name='книги автора')
    
    def __str__(self):
        return f'{self.title}'

class About(models.Model):

    class Meta:
        verbose_name = 'о нас'
        verbose_name_plural = 'о нас'

    title = models.CharField(max_length=300, verbose_name='заголовок')
    image = models.ImageField(verbose_name='изображение', upload_to='image/', null=True)
    content =  models.TextField(verbose_name='контент')


# Create your models here.

book/report/views.py
from turtle import title
from email.mime import image
from django.conf import settings
from django.forms import FileField
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from report.models import *
from django.http import HttpResponse
from report.models import Book
from django.conf import os

booksImageSystem = FileSystemStorage('media/images/')
booksFileSystem = FileSystemStorage('media/file/')


def home(request): 
    report = Book.objects.all()[:5]
    return render(request, 'home.html', {'home': report})

def books(request):
    report = Book.objects.all()
    return render(request, 'book.html', {'books': report})

def avtors(request, id):
    report = Avtor.objects.filter(title=id)
    # report = Works.objects.filter(title=id)
    return render(request, 'author.html', {'avtors': report})

def authors(request):
    report = Avtor.objects.all()
    return render(request, 'authors.html', {'authors': report})

def aboute(request):
    report = About.objects.all()
    return render(request, 'about.html', {'aboute': report})

def category(request):
    book = Book.objects.all()
    categories = Categories.objects.all()
    return render(request, 'categories_b.html', {
        'book': book,
        'categories': categories
        })

def fiter_book(request, id):
    books = Book.objects.filter(category__id=id)
    return render(request, 'janry.html', {'books': books})

def item_books(request, id):
    books = Book.objects.get(id=id)
    categories = Categories.objects.all()
    return render(request, 'item_books.html', {'books': books, 'categories': categories})


def search_books(request):
    title = request.GET.get('search')
    authors = Avtor.objects.filter(title__icontains=title)
    books  = Book.objects.filter(title__icontains=title)
    return render(request, 'search.html',{
        'books': books, 
        'authors': authors,
        'categories': Categories.objects.all(), 
        'title': title
    })


def login_profile(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('/')
        return render(request, 'auth/login.html', {})
    return redirect('/')


def logout_profile(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('/')

def my_books(request):
    books = Book.objects.filter(author_site=request.user)
    categories = Categories.objects.all()
    return render(request, 'my_books/my_books.html', {'books': books, 'categories': categories})

def create_books(request):

    if request.method == 'POST':

        title = request.POST.get('title')
        # author = request.POST.get('author')
        image = request.FILES['image']
        file = request.FILES['file']
        category = Categories.objects.get(id=request.POST.get('category'))
        author = Avtor.objects.get(id=request.POST.get('author'))
        print(author)
        desc = request.POST.get('description')   
        booksImageSystem.save(image.name, image)
        booksFileSystem.save(file.name, file)
        books = Book.objects.create(
            title = title,
            image = image,
            category = category,
            author = author,
            desc = desc,
            file = file,
            author_site=request.user
        )
        books.save()

        return redirect('/my_books/')
    author = Avtor.objects.all()
    categories = Categories.objects.all()
    return render(request, 'my_books/create_books.html', {'categories': categories, 'author': author,})
    
# def janry(request):
#     category = Categories.objects.all()
#     #news = News.objects.filter(category__slug=slug)
#     books = Book.objects.filter(category=category)
#     categories = Categories.objects.all()
#     return render(request, 'janry.html',{
#         'books': books, 
#         'categories': categories, 
#         'category': category,
#     })

# def download(request, path):
#     file_path=os.path.join(settings.MEDIA_ROOT,path)
#     if os.path.exists(file_path):
#         with open(file_path, 'rb')as fh:
#             response=HttpResponse(fh.read(),content_type="application/file")
#             response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
#             return response

#     raise 
# Create your views here.

book/templates/about.html
{% extends 'base.html' %}
{% block content %}

<div class="d-flex position-relative p-3">
  {% for item in aboute %}
    <div class="p-2">
      <h5 class="text-center mt-5">{{ item.title }}</h5>
      <p>{{ item.content }}</p>
      <div class="container" style="width: 30rem;">
        <img src="{{ item.image.url }}" class="img-fluid rounded mx-auto d-block" width:"350px" alt="...">
      </div>
    </div>
    {% endfor %}
  </div>
  
{% endblock content %}

book/templates/author.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="container">
<div class="mb-3 m-5 shadow-none p-3 mb-5 bg-light rounded" style="max-width: 740px;">
  {% for item in avtors %}
    <div class="row p-4">
      <div class="col-3">
        {% if item.img_Avtor %}
            <img src="{{ item.img_Avtor.url }}" class="img-fluid rounded-start" width="200px" alt="...">
        {% else %}
            <img src="{% static 'down/image/author.webp'%}" width="200px" class="img-fluid rounded-start" alt="...">
        {% endif %}
        <p class="text-center">({{ item.year_avtor}}г)</p>
      </div>
      <div class="col-9">
        <div class="card-body">
          <h5 class="card-title">{{ item.title }}</h5>
          <p class="card-text">{{ item.avtor }}</p> 
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% comment %} <div class="container">
  {% for item in avtors %}
  <button type="button" class="btn btn-secondary mb-3">
    Книги <span class="badge bg-primary"> {{ item.info.all.count}}</span>
  </button>
  <div class="card mb-3 m-5" style="max-width: 300px ;">
    <div class="d-flex flex-row bd-highlight mb-3">
    {% for tag in item.info.all %}
          <div class="p-3">
            {% if tag.image %}
            <img src="{{ tag.image.url }}" class="img-fluid rounded-start" width="200px" alt="...">
        {% else %}
            <img src="{% static 'down/image/book.webp'%}" width="200px" class="img-fluid rounded-start" alt="...">
        {% endif %}
          <h6 class="text-decoration-none text-dark">{{ tag.title }}</h6> 
          <p>{{ tag.year }}</p>
          <p>{{ tag.content }}</p>
            </div  
          {% endfor %} 
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  </div> {% endcomment %}
  
  <div class="conatiner m-4">
    <div class="row p-3">
      {% for item in avtors %}
      <button type="button" class="btn btn-secondary mb-3">
        Книги <span class="badge bg-primary"> {{ item.info.all.count}}</span>
      </button>
      {% for tag in item.info.all %}
      <div class="col-3">
        <div class="card" style="width: 12rem;">
          <img src="{{ tag.image.url }}" height="240px" class="card-img-top" alt="...">
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ tag.title }}</h5>
          <a class="text-decoration-none text" href="#">год издания: {{ tag.year }}</a>
          <h6 class="card-title">{{ tag.content }}</h6>
      </div> 
      </div>
      {% endfor %}
      {% endfor %}
    </div>
  </div>
{% endblock content %}

book/templates/authors.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    {% for item in authors %}
<div class="mb-3 m-5 shadow-none p-3 mb-5 bg-light rounded" style="max-width: 940px;">
    <div class="row p-4">
      <div class="col-3">
        {% if item.img_Avtor %}
            <img src="{{ item.img_Avtor.url }}" class="img-fluid rounded-start" width="200px" alt="...">
        {% else %}
            <img src="{% static 'down/image/author.webp'%}" width="200px" class="img-fluid rounded-start" alt="...">
        {% endif %}
        <p class="text-center">({{ item.year_avtor}}г)</p>
      </div>
      <div class="col-9">
        <div class="card-body">
          <a class="text-decoration-none text" href="{% url 'avtors' id=item.info %}">{{ item.title }}</a>
          <p class="card-text">{{ item.avtor }}</p> 
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

book/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link type="text/css" href="{% static 'down/css/style.css' %}" rel="stylesheet" />
    <link rel="icon" type="image/png" href="{% static 'down/image/favicon.ico' %}">
    <title>Библиотека {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% comment %} <script src="{% static 'js/script.js'%}"></script> {% endcomment %}
    <link rel="stylesheet" title="theme" href="#">
</head>
<body>
    {% include 'components/navbar.html' %}
    <main>
        {% block content %}{% endblock content %}
    </main>
    {% include 'components/footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

book/templates/book.html
{% extends 'base.html' %}
{% block content %}

<div class="album py-5 bg">
<div class="container">
  <button type="button" class="btn btn-secondary mb-3">
    Книги <span class="badge bg-primary"> {{ books.count }}</span>
  </button>
      {% for item in books %}
      <div class="shadow p-3 mb-5 bg-white rounded">
      <div class="row">
      <div class="col-2">
        <div class="shadow bg-white "  style="width: 9rem;">
          <img src="{{ item.image.url }}" height="180px" class="card-img-top" alt="...">
        </div>
      </div>
      <div class="col-10">
        <div class="card-body">
          <h5 class="card-title">{{ item.title }}</h5>
          <a class="text-decoration-none text" href="{% url 'avtors' id=item.author %}">{{ item.author }}</a>
          <p>{{ item.desc }}</p>
          <div><a class="text-decoration-none text-info" href="{% url 'fiter_book' id=item.category.id %}">Жанры: {{ item.category.title }}</a></div>
          <a href="{{ item.file.url }}" target="_blank" class="btn btn-sm btn-outline-secondary my-3">Читать книгу...</a>
          <div class="float-end text-muted">{{ item.date }}</div><br>

        </div>
      </div>
      </div>
  </div>
  {% endfor %}
</div>
</div>


{% comment %} <div class="album py-5 bg-light">
  <div class="container">  
    <div class="row">
      {% for item in books %}
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ item.image.url }}" alt="" class="w-100">
              <div class="card-body">
                <p class="card-text">{{ item.title }} {{ item.id }}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{{ item.file.url }}" target="_blank" class="btn btn-sm btn-outline-secondary">View</a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
      {% endfor %}
      </div>
    </div>
  </div>
</div> {% endcomment %}

{% endblock content %}

book/templates/categories_b.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-3 mb-3">
  <h1>{{ title }}</h1>
  <div class="row">
    
    <div class="col-md-4">
      <div class="list-group">
        <div class="card-header">
          <h5>Категортии</h5>
        </div>
        {% for item in categories %}
          <a href="{% url 'fiter_book' id=item.id %}" class="list-group-item list-group-item-action">{{ item.title }}</a>
        {% endfor %}
      </div>
    </div>

    <div class="col-md-8">
      {% for item in book %}
      <div class="shadow p-3 mb-5 bg-white rounded">
      <div class="row">
      <div class="col-3">
        <div class="shadow bg-white "  style="width: 9rem;">
          <img src="{{ item.image.url }}" height="180px" class="card-img-top" alt="...">
        </div>
      </div>
      <div class="col-5">
        <div class="card-body">
          <h5 class="card-title">{{ item.title }}</h5>
          <a class="text-decoration-none text" href="{% url 'avtors' id=item.author %}">{{ item.author }}</a>
          <p>{{ item.desc }}</p>
          <div><a class="text-decoration-none text-info" href="{% url 'fiter_book' id=item.category.id %}">Жанры: {{ item.category.title }}</a></div>
          <a href="{{ item.file.url }}" target="_blank" class="btn btn-sm btn-outline-secondary my-3">Читать книгу...</a>
        </div>
      </div>
      </div>
  </div>
  {% endfor %}
  </div>
</div>
{% endblock content %}

book/templates/components/footer.html
{% load static %}
<div class=" p-2 bg-light">
    <div class="row row-cols-4">
      <div class="col"><div class="">
        <a class="navbar-brand p-3" href="#">
          <img src="{% static 'down/image/logo1.png'%}" alt="" width="70" height="70" class="d-inline-block align-text-top">
        </a>
      </div></div>
      <div class="col">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="{% url 'books' %}">Книги</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="{% url 'category'  %}">Жанры</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="{% url 'authors' %}">Авторы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="{% url 'aboute' %}">О нас</a>
          </li>
        </ul>
      </div>
      <div class="col">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Контакты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">+996700800800</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">+996700700700</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">library@gmail.com</a>
          </li>
        </ul>
      </div>
      <div class="col">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Соц сети</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">Instagram</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">Telegram</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-secondary" href="#">Facebook</a>
          </li>
        </ul>
      </div>
    </div>
  </div>

book/templates/components/navbar.html
{% load static %}
<div class="bg-light">
    <div class="container">
      <div class="row py-2">
        <div class="col">
         <div class="row">
          {% if request.user.is_authenticated %}
          <div class="col-2 py-2 nav">
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ request.user.username }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a href="" class="dropdown-item">Мой профиль</a></li>
              <li><a href="{% url 'my_books'%}" class="dropdown-item">Личный кабинет</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a href="{% url 'logout' %}" class="dropdown-item">Выход</a></li>
            </ul>
            </li>        
          </div>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Вход</a></li>
          {% comment %} <div class="col-2 py-2">
            <a class="nav-item"><a class="nav-link text-secondary" href="">Регистрация</a></a>
          </div> {% endcomment %}
          {% endif %}
         </div>
        </div>
        <div class="col">
          <img src="{% static 'down/image/logo1.png'%}" class="rounded mx-auto d-block " width="70" alt="...">
        </div>
        <div class="col col-lg-4">
          <form action="{% url 'search_books' %}" method="GET" class="d-flex p-2">
            <input class="form-control me-2" type="search" placeholder="Поиск книг..." aria-label="Search" name="search">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
          </form>
        </div>
      </div>
    </div>
  </div>

    <ul class="nav justify-content-center bg-primary">
      <li class="nav-item">
        <a class="nav-link text-light" aria-current="page" href="{% url 'home' %}">Главная</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'books' %}">Книги</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'category'  %}">Жанры</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active text-light" href="{% url 'authors' %}">Авторы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active text-light" href="{% url 'aboute' %}">О нас</a>
      </li>
    </ul>

book/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item carousel-item1 active">
            <div class="carousel-caption d-none d-md-block">
              <h5>Чтение книг — не способ бегства от жизни, книги дают ключ к ее пониманию. Ключ к реальности.</h5>
              <p>Себастьян Фолкс</p>
            </div>
          </div>
          <div class="carousel-item carousel-item2">
            <div class="carousel-caption d-none d-md-block">
              <h5>Чтение чрезвычайно помогает, а книги — хорошая компания, если взять самые подходящие.</h5>
              <p>Луиза Мэй Олкотт</p>
            </div>
          </div>
          <div class="carousel-item carousel-item3">
            <div class="carousel-caption d-none d-md-block">
              <h5> Я уверен: книгу ничто не заменит в будущем, так же как ничто не могло заменить её в прошлом.</h5>
              <p>Айзек Азимов</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"  data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Предыдущий</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"  data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Следующий</span>
        </button>
      </div>

      <div class="d-flex position-relative p-3">
        <img src="{% static 'down/image/book-main.jpg'%}" class="img-fluid rounded-start" alt="...">
        <div class="p-2">
          <h5 class="mt-5">Почему электронные книги ещё не умерли?</h5>
          <p>Электронные книги за последний десяток лет отошли на второй план. Отчасти потому что их заменили смартфоны, отчасти потому что люди перестали читать. Конечно, ведь ответы на все вопросы есть в интернете, а развлекать себя сериалами куда приятнее. Несколько месяцев назад в нашем распоряжении оказалась Amazon Kindle 2019 года 10-го поколения и это простое, но исчерпывающее устройство, навеяло некоторые мысли о таком почти забытом рынке цифровых книг.</p>
          <a href="#" class="stretched-link">Подробнее</a>
        </div>
      </div>
      

      <div class="conatiner m-4">
      <div class="row p-3">
        <h4 class="text-primary">Новые</h4>
        {% for item in home %}
        <div class="col">
          <div class="card" style="width: 12rem;">
            <img src="{{ item.image.url }}" height="240px" class="card-img-top" alt="...">
          </div>
          <div class="card-body">
          <h6><a href="{{ item.file.url }}" target="_blank" class=" btn-outline-secondary my-3">{{ item.title }}</a></h6>
          <a class="text-decoration-none text" href="{% url 'avtors' id=item.author %}">{{ item.author }}</a>
        </div> 
        </div>
        {% endfor %}
      </div>
    </div> 

      {% endblock content %}

book/templates/janry.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="album py-5 bg">
  <div class="container">
    <button type="button" class="btn btn-secondary mb-3">
      Книги <span class="badge bg-primary"> {{ books.count }}</span>
    </button>
        {% for item in books %}
        <div class="shadow p-3 mb-5 bg-white rounded">
        <div class="row">
        <div class="col-2">
          <div class="shadow bg-white "  style="width: 9rem;">
            <img src="{{ item.image.url }}" height="180px" class="card-img-top" alt="...">
          </div>
        </div>
        <div class="col-10">
          <div class="card-body">
            <h5 class="card-title">{{ item.title }}</h5>
            <a class="text-decoration-none text" href="{% url 'avtors' id=item.author %}">{{ item.author }}</a>
            <p>{{ item.desc }}</p>
            <div><a class="text-decoration-none text-info" href="{% url 'fiter_book' id=item.category.id %}">Жанры: {{ item.category.title }}</a></div>
            <a href="{{ item.file.url }}" target="_blank" class="btn btn-sm btn-outline-secondary my-3">Читать книгу...</a>
          </div>
        </div>
        </div>
    </div>
    {% endfor %}
  </div>
  </div>
  
{% endblock content %}

book/templates/my_books/create_books.html
{% extends 'base.html' %}
{% block title %}| Добавление{% endblock title %}
{% block content %}

<div class="album py-5 bg-light">
    <div class="container py-5">  
        <h3 class="mb-5 text-center">Добавление </h3>
        {% comment %} action="{% url 'create_books' %}" {% endcomment %}
        <form  method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-12 mb-3">
                    <label for="id_title">Заголовок <span class="text-danger">*</span></label>
                    <input type="text" name="title" id="id_title" class="form-control" required>
                </div> 
                <div class="col-md-6 col-12">
                    <label for="id_iamge">Изображение <span class="text-danger">*</span></label>
                    <input type="file" name="image" class="form-control" id="id_iamge" required>
                </div>

                 <div class="col-md-6 col-12">
                    <label for="id_iamge">Файл <span class="text-danger">*</span></label>
                    <input type="file" name="file" class="form-control" id="id_file" required>
                </div> 
                <div class="col-md-6 col-12">
                    <label for="id_category">Категория <span class="text-danger">*</span></label>
                    <select name="author" class="form-control" id="id_category required">
                        <option disabled >Выберите author</option>
                        {% for category in author %}
                            <option value="{{ category.id }}">{{ category.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-12 mb-3">
                    <label for="id_title">Desc <span class="text-danger">*</span></label>
                    <input type="text" name="description" id="id_title" class="form-control" required>
                </div> 
                <div class="col-md-6 col-12">
                    <label for="id_category">Категория <span class="text-danger">*</span></label>
                    <select name="category" class="form-control" id="id_category required">
                        <option disabled >Выберите категорию</option>
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.title }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="d-grid gap-2 col-6 mx-auto p-3">
                    <button class="btn btn-primary" type="submit">Добавить</button>
                  </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}